version: '3.8'

services:
  db:
    container_name: herepoon_container
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tewme
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  pgadmin:
    container_name: adminpoon_container
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config_local.py:/pgadmin4/config_local.py
      - ./init_files:/init_files
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh && /entrypoint.sh"]

volumes:
  pgdata:
  pgadmin-data:
